name: Publish Docker image

on:
  push:
    tags:
      - '*'

jobs:

  publish:
    name: Publish Docker image
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Parse tag
        id: parse_tag
        uses: michielkempen/regex-matcher@v1.2
        with:
          regex_pattern: '^refs/tags/([a-z-]+)-([0-9.]+)-([0-9.]+)$'
          search_string: ${{ github.ref }}

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ${{ steps.parse_tag.outputs.match_0 }}/${{ steps.parse_tag.outputs.match_1 }}
          push: true
          tags: |
            smoothy/${{ steps.parse_tag.outputs.match_0 }}:${{ steps.parse_tag.outputs.match_1 }}-${{ steps.parse_tag.outputs.match_2 }}
            smoothy/${{ steps.parse_tag.outputs.match_0 }}:${{ steps.parse_tag.outputs.match_1 }}
